Revert "Upgrade deps (#569)"
deso-protocol/backend pull request #630
Opened 2024-06-04 00:00 UTC by tholonious

This reverts commit 9f108080ed8b13d8b0f7907539fc942e96fb32f3.

2024-06-04 00:00 UTC, tholonious commented
* **#630** <a href="https://app.graphite.dev/github/pr/deso-protocol/backend/630?utm_source=stack-comment-icon" target="_blank"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="10px" height="10px"/></a> 👈
* `feature/proof-of-stake`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @tholonious and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment"><img src="https://static.graphite.dev/graphite-32x32-black.png" alt="Graphite" width="11px" height="11px"/> <b>Graphite</b></a>
  <!-- Current dependencies on/for this PR: -->

2024-06-05 21:39 UTC, lazynina requested changes

2024-06-05 21:39 UTC, lazynina commented on routes/dao_coin_exchange.go
> -	if IsDesoPkid(buyingCoinPublicKeyBase58Check) {
I think there was some other reason DH wanted this change. I think it matches both DESO and the zero public key

2024-06-05 21:39 UTC, lazynina commented on routes/dao_coin_exchange.go
> +	if sellingDAOCoinCreatorPublicKeyBase58Check == DESOCoinIdentifierString {
Same here with the IsDESOPKID

2024-06-05 21:39 UTC, lazynina commented on routes/dao_coin_exchange.go
> -	if IsDesoPkid(coinCreatorPublicKeyBase58Check) {
IsDesoPkid should stay I think

2024-06-05 22:12 UTC, lazynina approved these changes

2024-06-05 22:13 UTC, merged