Add decentralized post pinning mechanism to backend.
deso-protocol/backend pull request #66
Opened 2021-06-30 03:25 UTC by bluepartyhat

2021-06-30 23:54 UTC, lazynina requested changes

2021-06-30 23:54 UTC, lazynina commented on routes/post.go
> +	// True if this post hash hex is in pinned globally.
```suggestion
	// True if this post hash hex is in pinned to the global feed.
```

2021-06-30 23:54 UTC, lazynina commented on routes/post.go
> +		IsGlobalPinned: 			&postEntry.IsGlobalPinned,
fix spacing -- don't use tabs.

2021-06-30 23:54 UTC, lazynina commented on routes/post.go
> +	// Fetch the commentEntries for the post.submit
```suggestion
	// Fetch the commentEntries for the post.
```

2021-06-30 23:54 UTC, lazynina commented on routes/post.go
> +	MaxPinnedPosts uint64 `safeForLogging:"true"`
what's the significance of MaxPinnedPosts?

2021-07-01 00:19 UTC, lazynina commented on routes/post.go
> +	MaxPinnedPosts uint64 `safeForLogging:"true"`
I think this can be rewritten to support returning all pinned posts? I tested pinning 20+ posts and only the top 5 appear as pinned.

2021-07-01 00:50 UTC, lazynina commented on routes/post.go
> +	// Get Pinned Posts Ordered by time. This also returns a postsIncluded map that we use to ignore
Let's add a comment explaining MaxPinnedPosts

2021-07-03 02:47 UTC, lazynina approved these changes

2021-07-03 02:47 UTC, lazynina commented
Need to run CI after core gets merged in to make sure tests pass.

2021-09-20 21:29 UTC, chafreaky commented
Bump on this. Barring the conflict, is there anything holding up this merge? It's a great feature!

2023-01-25 02:20 UTC, closed without merging